# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
before_install:
- chmod +x ./travis-scripts/*.sh
install:
- ./travis-scripts/install.sh
script:
- ./travis-scripts/build.sh
